### ISSUE TITLE
Launcher doesn't work when another Edge-instance is already open.

### ISSUE THREAD

**Issue by tivoa-gigatronik** [MicrosoftEdge/edge-launcher#15]
When I start any link or file (e.g. pdf) for the first time, it works perfectly.
But when I run the launcher again while one instance of Edge is open, it opens an empty Edge browser but the link doesn't open in any of the new running instances.

**Comment by nickmccurdy** [comment]
Do you still have this problem with the `-k` flag?

**Comment by auchenberg** [comment]
This should have been resolved. Closing for now.
