### ISSUE TITLE
-k flag appears to behave inconsistently if the URL is not given

### ISSUE THREAD

**Issue by nicolasmccurdy** [MicrosoftEdge/edge-launcher#18]
It seems as if using the `-k` flag without a URL causes the launch to open `-k` as the URL, ignoring the keepalive option.

## Reproduction
Run `MicrosoftEdgeLauncher.exe -k`.

## Expected behavior
* A new instance of Edge launches with the usual start page.
* The command waits to complete.

## Actual behavior
* Edge opens with a blank window (it seems like a minor UI glitch, it's not the start page).
* The command does not wait to complete.

**Comment by andysterland** [comment]
Thanks for the repo. I'll take a look at it as it should launch to the default URL.
