### ISSUE TITLE
npm package version seems to be out of date

### ISSUE THREAD

**Issue by nickmccurdy** [MicrosoftEdge/edge-launcher#20]
I've noticed a 1.2 release on this GitHub repo, but npm seems to only have versions 1.0.0 and 1.0.1. If you're interested in automating these releases, check out [karma-ie-launcher's Gruntfile](https://github.com/karma-runner/karma-ie-launcher/blob/master/gruntfile.js), it has some tasks for automating version bumps, GitHub releases, and npm publishes together.

Also, can you please add the published `package.json` to this repo's source (to make it easier to fork and to allow npm installs of unpublished commits through GitHub)?

**Comment by nickmccurdy** [comment]
As mentioned in [my comment on #22](https://github.com/MicrosoftEdge/edge-launcher/issues/22#issuecomment-285748043), I would be happy to fix this issue if a maintainer is comfortable with giving me access to it on npm.

**Comment by auchenberg** [comment]
NPM has hereby been updated.
